### ISSUE TITLE
db:migrate Issue on Installing kms on Rails 4.2.7 Project

### ISSUE THREAD

**Issue by andisugandi** [webgradus/kms#3]
There is an issue after running: RAILS_ENV=development bin/rake db:migrate :

```
Running via Spring preloader in process 6023
== 20160727081524 CreatePages: migrating ======================================
-- create_table(:kms_pages)
   -> 0.0017s
== 20160727081524 CreatePages: migrated (0.0018s) =============================

== 20160727081525 CreateTemplates: migrating ==================================
-- create_table(:kms_templates)
   -> 0.0014s
== 20160727081525 CreateTemplates: migrated (0.0015s) =========================

== 20160727081526 AddTemplateIdToPages: migrating =============================
-- add_column(:kms_pages, :template_id, :integer)
   -> 0.0009s
== 20160727081526 AddTemplateIdToPages: migrated (0.0010s) ====================

== 20160727081527 CreateAssets: migrating =====================================
-- create_table(:kms_assets)
   -> 0.0012s
== 20160727081527 CreateAssets: migrated (0.0013s) ============================

== 20160727081528 AddAncestryToPages: migrating ===============================
-- add_column(:kms_pages, :ancestry, :string)
   -> 0.0008s
-- add_index(:kms_pages, :ancestry)
   -> 0.0011s
== 20160727081528 AddAncestryToPages: migrated (0.0021s) ======================

== 20160727081529 DeviseCreateUsers: migrating ================================
-- create_table(:kms_users)
   -> 0.0027s
-- add_index(:kms_users, :email, {:unique=>true})
   -> 0.0010s
-- add_index(:kms_users, :reset_password_token, {:unique=>true})
   -> 0.0017s
== 20160727081529 DeviseCreateUsers: migrated (0.0057s) =======================

== 20160727081530 AddFullpathToPages: migrating ===============================
-- add_column(:kms_pages, :fullpath, :string)
   -> 0.0005s
== 20160727081530 AddFullpathToPages: migrated (0.0006s) ======================

== 20160727081531 AddRoleToUsers: migrating ===================================
-- add_column(:kms_users, :role, :string)
   -> 0.0009s
== 20160727081531 AddRoleToUsers: migrated (0.0010s) ==========================

== 20160727081532 AddTemplatableFieldsToPages: migrating ======================
-- add_column(:kms_pages, :templatable, :boolean, {:default=>false})
   -> 0.0012s
-- add_column(:kms_pages, :templatable_type, :string)
   -> 0.0006s
== 20160727081532 AddTemplatableFieldsToPages: migrated (0.0020s) =============

== 20160727081533 AddHiddenToPage: migrating ==================================
-- add_column(:kms_pages, :hidden, :boolean, {:default=>false})
   -> 0.0010s
== 20160727081533 AddHiddenToPage: migrated (0.0011s) =========================

== 20160727081534 AddPositionToKmsPages: migrating ============================
-- add_column(:kms_pages, :position, :integer, {:default=>0, :null=>false})
   -> 0.0010s
== 20160727081534 AddPositionToKmsPages: migrated (0.0011s) ===================

== 20160727081535 CreateKmsSnippets: migrating ================================
-- create_table(:kms_snippets)
   -> 0.0007s
== 20160727081535 CreateKmsSnippets: migrated (0.0008s) =======================

== 20160727081536 CreateKmsSettings: migrating ================================
-- create_table(:kms_settings)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x005588484c5998>
Did you mean?  JSON
/home/siswa/Documents/Projects/Rails/cmskms/db/migrate/20160727081536_create_kms_settings.kms.rb:5:in `block in change'
/home/siswa/Documents/Projects/Rails/cmskms/db/migrate/20160727081536_create_kms_settings.kms.rb:4:in `change'
-e:1:in `<main>'
NoMethodError: undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x005588484c5998>
Did you mean?  JSON
/home/siswa/Documents/Projects/Rails/cmskms/db/migrate/20160727081536_create_kms_settings.kms.rb:5:in `block in change'
/home/siswa/Documents/Projects/Rails/cmskms/db/migrate/20160727081536_create_kms_settings.kms.rb:4:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Here is a [Gemfile](http://paste.opensuse.org/view/simple/17069693).

Any suggestion?

**Comment by andisugandi** [comment]
The [Gemfile.lock](http://paste.opensuse.org/view/simple/9772883).

**Comment by GarPit** [comment]
Hello, @andisugandi. Glad you're trying KMS, going to add more detailed documentation soon.

What database adapter do you use? KMS expects using PostgreSQL database

**Comment by andisugandi** [comment]
My (silly) mistake, forgot to make the database before following the guide.

The issue is now solved.

Thank you, @GarPit and team.
